// Package logstream fans out a job's live output to anyone watching it.
//
// Two rules shape this package, and they are in tension.
//
// First: a viewer must never slow down a job. Log streaming is an observability
// feature, and observability that applies backpressure to the thing it observes
// has become a liability. A subscriber on a bad connection, or one that stopped
// reading, must be degraded — never the job.
//
// Second: silently dropping output is dishonest. An operator reading a log that
// quietly omits lines will draw wrong conclusions from it, which is worse than
// an operator who knows they are missing something.
//
// So slow subscribers lose lines, and are told exactly how many. The durable
// record is separate: drivers write every line to disk, so the complete log is
// always recoverable after the fact. This package is the live tail, not the
// system of record.
package logstream

import (
	"context"
	"fmt"
	"sync"
	"time"

	"ephemera/internal/driver"
)

// DefaultHistorySize is how many recent lines a new subscriber receives.
//
// It exists because viewers arrive late. Someone opening a dashboard thirty
// seconds into a job wants to see what has happened, not an empty pane until
// the next line appears.
const DefaultHistorySize = 500

// DefaultSubscriberBuffer is the per-subscriber queue depth before lines are
// dropped for that subscriber.
const DefaultSubscriberBuffer = 256

// Broker fans out log lines per job. Safe for concurrent use.
type Broker struct {
	historySize int
	bufferSize  int
	now         func() time.Time

	mu     sync.RWMutex
	topics map[string]*topic
}

type topic struct {
	// history is a ring buffer of recent lines, so a late subscriber has
	// context rather than an empty screen.
	history []driver.LogLine
	// ended reports that the job finished and no more lines will arrive.
	ended bool
	subs  map[*subscriber]struct{}
}

type subscriber struct {
	ch chan driver.LogLine

	mu      sync.Mutex
	dropped int
	closed  bool
}

// Option configures a Broker.
type Option func(*Broker)

// WithHistorySize sets how many recent lines a new subscriber replays.
func WithHistorySize(n int) Option {
	return func(b *Broker) { b.historySize = n }
}

// WithSubscriberBuffer sets the per-subscriber queue depth.
func WithSubscriberBuffer(n int) Option {
	return func(b *Broker) { b.bufferSize = n }
}

// WithClock overrides the time source.
func WithClock(now func() time.Time) Option {
	return func(b *Broker) { b.now = now }
}

// NewBroker creates a broker.
func NewBroker(opts ...Option) *Broker {
	b := &Broker{
		historySize: DefaultHistorySize,
		bufferSize:  DefaultSubscriberBuffer,
		now:         time.Now,
		topics:      map[string]*topic{},
	}
	for _, opt := range opts {
		opt(b)
	}
	return b
}

func (b *Broker) topicFor(jobID string) *topic {
	if t, ok := b.topics[jobID]; ok {
		return t
	}
	t := &topic{subs: map[*subscriber]struct{}{}}
	b.topics[jobID] = t
	return t
}

// Publish delivers a line to every current subscriber and records it in history.
//
// Never blocks. A subscriber whose buffer is full loses the line and has its
// drop counter incremented; the job carries on regardless.
func (b *Broker) Publish(jobID string, line driver.LogLine) {
	b.mu.Lock()
	defer b.mu.Unlock()

	t := b.topicFor(jobID)
	t.history = append(t.history, line)
	if len(t.history) > b.historySize {
		// Keep the most recent window. Reslicing rather than reallocating each
		// time keeps this cheap on the hot path.
		t.history = t.history[len(t.history)-b.historySize:]
	}

	for sub := range t.subs {
		sub.send(line)
	}
}

// send delivers a line without ever blocking the publisher.
func (s *subscriber) send(line driver.LogLine) {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return
	}
	dropped := s.dropped
	s.mu.Unlock()

	// If lines were previously dropped, tell the subscriber before delivering
	// this one. A log with a visible gap marker is honest; one with an
	// invisible gap is misleading.
	if dropped > 0 {
		notice := driver.LogLine{
			At:     line.At,
			Stream: StreamNotice,
			Text:   fmt.Sprintf("[%d lines dropped: this viewer could not keep up]", dropped),
		}
		select {
		case s.ch <- notice:
			s.mu.Lock()
			s.dropped = 0
			s.mu.Unlock()
		default:
			// Still full. Count this line as dropped too and move on.
			s.mu.Lock()
			s.dropped++
			s.mu.Unlock()
			return
		}
	}

	select {
	case s.ch <- line:
	default:
		s.mu.Lock()
		s.dropped++
		s.mu.Unlock()
	}
}

// StreamNotice marks lines generated by the platform rather than the agent, so
// a consumer can style or filter them apart from real output.
const StreamNotice = "notice"

// Subscribe returns a channel of log lines for a job, beginning with recent
// history and continuing live.
//
// The returned cancel function must be called to release the subscription. The
// channel closes when the job's stream ends or the subscription is cancelled.
func (b *Broker) Subscribe(ctx context.Context, jobID string) (<-chan driver.LogLine, func()) {
	b.mu.Lock()
	t := b.topicFor(jobID)

	sub := &subscriber{ch: make(chan driver.LogLine, b.bufferSize)}

	// Snapshot history and register the subscriber under one lock. Doing these
	// separately would drop any line published in between, or deliver it twice.
	history := make([]driver.LogLine, len(t.history))
	copy(history, t.history)
	alreadyEnded := t.ended
	if !alreadyEnded {
		t.subs[sub] = struct{}{}
	}
	b.mu.Unlock()

	out := make(chan driver.LogLine, len(history)+b.bufferSize)

	var once sync.Once
	cancel := func() {
		once.Do(func() {
			b.mu.Lock()
			delete(t.subs, sub)
			b.mu.Unlock()

			// End may already have closed this channel. sync.Once guards
			// against cancel being called twice, but not against End and
			// cancel both firing, which is the ordinary case: a job finishes
			// while a viewer is still attached, and the viewer then detaches.
			sub.mu.Lock()
			if !sub.closed {
				sub.closed = true
				close(sub.ch)
			}
			sub.mu.Unlock()
		})
	}

	go func() {
		defer close(out)

		for _, line := range history {
			select {
			case out <- line:
			case <-ctx.Done():
				cancel()
				return
			}
		}

		if alreadyEnded {
			// The job finished before this viewer arrived. History was the
			// whole story; there is nothing live to wait for.
			cancel()
			return
		}

		for {
			select {
			case line, ok := <-sub.ch:
				if !ok {
					return
				}
				select {
				case out <- line:
				case <-ctx.Done():
					cancel()
					return
				}
			case <-ctx.Done():
				cancel()
				return
			}
		}
	}()

	return out, cancel
}

// End marks a job's stream as finished, closing every subscriber's channel.
//
// History is retained so a viewer arriving afterwards still sees the tail of
// what happened. Forget releases it.
func (b *Broker) End(jobID string) {
	b.mu.Lock()
	defer b.mu.Unlock()

	t, ok := b.topics[jobID]
	if !ok {
		return
	}
	t.ended = true
	for sub := range t.subs {
		sub.mu.Lock()
		if !sub.closed {
			sub.closed = true
			close(sub.ch)
		}
		sub.mu.Unlock()
		delete(t.subs, sub)
	}
}

// Forget releases a job's history and topic.
//
// Called when a job's record is no longer needed live — after artifacts are
// stored and the durable log is on disk. Without it, a long-running control
// plane accumulates history for every job it has ever run, which is a slow
// memory leak that only shows up in production.
func (b *Broker) Forget(jobID string) {
	b.End(jobID)
	b.mu.Lock()
	defer b.mu.Unlock()
	delete(b.topics, jobID)
}

// History returns the retained lines for a job.
func (b *Broker) History(jobID string) []driver.LogLine {
	b.mu.RLock()
	defer b.mu.RUnlock()

	t, ok := b.topics[jobID]
	if !ok {
		return nil
	}
	out := make([]driver.LogLine, len(t.history))
	copy(out, t.history)
	return out
}

// Ended reports whether a job's stream has finished.
func (b *Broker) Ended(jobID string) bool {
	b.mu.RLock()
	defer b.mu.RUnlock()
	t, ok := b.topics[jobID]
	return ok && t.ended
}

// SubscriberCount reports how many viewers are attached to a job, for metrics
// and for tests.
func (b *Broker) SubscriberCount(jobID string) int {
	b.mu.RLock()
	defer b.mu.RUnlock()
	t, ok := b.topics[jobID]
	if !ok {
		return 0
	}
	return len(t.subs)
}

// Note emits a platform-generated line into a job's stream. Used to record
// lifecycle events — provisioning, retries, reaping — in the same timeline as
// the agent's own output, so an operator reads one story rather than two.
func (b *Broker) Note(jobID, format string, args ...any) {
	b.Publish(jobID, driver.LogLine{
		At:     b.now(),
		Stream: StreamNotice,
		Text:   fmt.Sprintf(format, args...),
	})
}
